-- Base locations table (shared with ROTAS Map). Required before 001 alters it.
CREATE TABLE IF NOT EXISTS locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  latitude numeric,
  longitude numeric,
  location_type text,
  created_year_start integer,
  created_year_end integer,
  discovered_year integer,
  script text,
  text text,
  place text,
  location text,
  first_word text,
  shelfmark text
);

ALTER TABLE locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read locations"
  ON locations FOR SELECT
  USING (true);
