-- User roles for monitor app access
CREATE TABLE IF NOT EXISTS user_profiles (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('editor', 'admin')),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Monitor check history
CREATE TABLE IF NOT EXISTS monitor_checks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checked_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL CHECK (status IN ('healthy', 'degraded', 'down')),
  map_http_status integer,
  map_response_ms integer,
  locations_count integer,
  locations_missing_coords integer,
  locations_invalid_years integer,
  locations_overlap_clusters integer,
  rpc_ok boolean,
  details jsonb,
  error_message text
);

-- Alerts raised by checks
CREATE TABLE IF NOT EXISTS monitor_alerts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  check_id bigint REFERENCES monitor_checks(id) ON DELETE CASCADE,
  severity text NOT NULL CHECK (severity IN ('warning', 'critical')),
  alert_type text NOT NULL,
  message text NOT NULL,
  acknowledged_at timestamptz,
  acknowledged_by uuid REFERENCES auth.users(id)
);

-- Location change audit trail
CREATE TABLE IF NOT EXISTS location_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id bigint,
  action text NOT NULL CHECK (action IN ('insert', 'delete')),
  actor_id uuid REFERENCES auth.users(id),
  payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE monitor_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE monitor_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE location_audit_log ENABLE ROW LEVEL SECURITY;

-- Helper: current user has editor or admin role
CREATE OR REPLACE FUNCTION is_monitor_user()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM user_profiles
    WHERE user_id = auth.uid()
    AND role IN ('editor', 'admin')
  );
$$;

CREATE OR REPLACE FUNCTION is_monitor_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM user_profiles
    WHERE user_id = auth.uid()
    AND role = 'admin'
  );
$$;

-- user_profiles policies
CREATE POLICY "Users read own profile"
  ON user_profiles FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Admins manage profiles"
  ON user_profiles FOR ALL
  USING (is_monitor_admin())
  WITH CHECK (is_monitor_admin());

-- monitor_checks policies
CREATE POLICY "Monitor users read checks"
  ON monitor_checks FOR SELECT
  USING (is_monitor_user());

-- monitor_alerts policies
CREATE POLICY "Monitor users read alerts"
  ON monitor_alerts FOR SELECT
  USING (is_monitor_user());

CREATE POLICY "Monitor users acknowledge alerts"
  ON monitor_alerts FOR UPDATE
  USING (is_monitor_user())
  WITH CHECK (is_monitor_user());

-- location_audit_log policies
CREATE POLICY "Monitor users read audit log"
  ON location_audit_log FOR SELECT
  USING (is_monitor_user());

CREATE POLICY "Monitor users insert audit log"
  ON location_audit_log FOR INSERT
  WITH CHECK (is_monitor_user());

-- locations write policies (public read assumed already exists)
CREATE POLICY "Monitor users insert locations"
  ON locations FOR INSERT
  WITH CHECK (is_monitor_user());

CREATE POLICY "Monitor users update location display coords"
  ON locations FOR UPDATE
  USING (is_monitor_user())
  WITH CHECK (is_monitor_user());

CREATE POLICY "Monitor users delete locations"
  ON locations FOR DELETE
  USING (is_monitor_user());
